### PR TITLE
Changed all /* */ comments to // so they don't appear in css output

### PR DESCRIPTION
**Pull request by meganox**
#34

### CODE REVIEW

**Comment by HellPat** [comment]
+1

**Comment by crispen-smith** [comment]
Why is this necessary?

```
[sudo] sass -watch foo:bar --compact 
```

removes _ALL_ comments, and anything less than --compact suggests the desire to keep some element of human readability should be left intact.

**Comment by patocallaghan** [comment]
Personally I do this in my projects as I didn't want all the inuit/grids comments appearing in my [Kalei Styleguide](http://kaleistyleguide.com/). I think [KSS](http://warpspire.com/posts/kss/) and [Styledocco](http://jacobrask.github.io/styledocco/) also operate on the same comment style.

**Comment by jqtrde** [comment]
@crispen-smith I don't think that's true. Just ran that myself and the comments are still there.

:+1: to this.

**Comment by meganox** [comment]
@crispen-smith  The comments are largely instructions on how to configure the SASS, they are pointless in the CSS output anyway. You could argue for keeping the single line comments next to individual rules I suppose.

**Comment by crispen-smith** [comment]
@meganox I'm all for having them out, I'm just suggesting that a code change might not be required, however @jacquestardie  seems to suggest that the --compact switch doesn't work the way it's documented, which is a separate sass issue.  I'm going to change my view on this and say +1

**Comment by csswizardry** [comment]
You’re after the `--compressed` flag, not `--compact`.

Comments should remain in code throughout development, and should only be removed once code is ready to be deployed, ergo, the removal of comments is a build step.

Thanks,
H

**Comment by meganox** [comment]
The comments are still there, in the sass, they are just removed from the generated css.  It is essential when writing sass to be able to view the generated css in a readable form, i.e. uncompacted, uncompressed and without meaningless comments.  

Sass doesn't provide a way to strip comments while keeping the output readable, but it does provide an alternate commenting style for sass-only comments. Personally I always use `//` comments in the sass source unless I specifically want the comments in the css output, so I would always write 
`$foo: false  // Set to true if you need fribble` 
and 
`.foo { zoom: 1 /* IE */ }` 
– it makes absolutely no sense in this case to see the comment `/* Set to true if you need fribble */` floating around in the css on its own after the code it applies to has disappeared.  

`//` comments should always be used for sass. Since css comments are stripped in the build anyway, `/**/` comments in sass are entirely pointless unless you have something you want your developers to be able to read in their intemediate development builds; personally I only use them for section headings: `/* § Fonts */`

Furthermore, this grid system is a library. Have a look at other libraries, you don't see Compass, for example, putting comments into the generated css, especially when they are only relevant to the sass and have nothing to do with the generated css.

**Pull request closed without merging**
