### PR TITLE
Add ability to define custom breakpoints

### PR DESCRIPTION
**Pull request by BPScott**
(Ab)use of Sass lists ahoy.

Using the $breakpoints variable users can define media groups in case they
need additional ones or would prefer a different naming convention to
the default provided.

This is slightly easier than declaring new breakpoints at the end of the file, and helps enforce the line between "customize the variables above this line" and "you won't need to modify anything below". Initial breakpoint declaration is slightly more verbose, but is more transparent and gives the user more power to customize them.

### CODE REVIEW

**Comment by asakurayoh** [comment]
I want that!

**Comment by csswizardry** [comment]
Sorry I’ve neglected this! I will merge this in manually at some point (I went and broke the ability to do an auto-merge :()

Cheers!

**Comment by BPScott** [comment]
Just rebased this onto latest master and resolved the conflict (whitespace caused by adding the `@if $responsive == true` check).

Auto merge should be good now.

**Comment by csswizardry** [comment]
Thanks!

Although now I need to marry that up with https://github.com/csswizardry/csswizardry-grids/commit/f7b5a2f09f63b62dbbade95c4c9d5dab878d61fa :(

I think I’ve gone and created myself a lot of work here >.<

**Comment by BPScott** [comment]
Yay two people developing at the same time. If you're happy with the current push/pull implementation I'll investigate how we can extend that with custom breakpoints.

Initial thoughts:
- $palm-push, $lap-push, $portable-push, $desk-push can be replaced with a list: `$hasPush: ('', 'palm', 'lap', 'portable', 'desk')` which shows the prefixes that want the push classes (with `''` being in there as unprefixed, which could probably be made more obvious).
- Same goes for the -pull variants.
- device-type, pull-setup and push-setup mixins could be combined by adding an additional 2 parameters in the style of:

```
@mixin grid-utility-builder($namespace: "", $utility:"", $property:"width"){
    #{$class-type}#{$utilty}push--#{$namespace}one-whole           { #{$property}:100%; }
    ...
}

// For unprefixed
@include grid-utility-builder("", '', "width");
@include grid-utility-builder("", '-push', "left");
@include grid-utility-builder("", '-pull', "right");
```

**Comment by BPScott** [comment]
Rebased on top of master again. Check the commit message as this slightly changes the behavior of $push and $pull. This commit doesn't abstract the device-type, pull-setup and push-setup mixins into a single mixin as it is unrelated.

**Comment by csswizardry** [comment]
Cherry picked this, gonna familiarise myself with it and get it merged in, thanks!

(It also fixes #1, AFAIK!)

**Comment by csswizardry** [comment]
Just recompiled the demo page locally using this; not a single thing changed in the compiled CSS :D

**Comment by emzo** [comment]
Very nice. I've been playing around with a similar idea for a while - wish I'd taken a look at this first!

Question: do you think it would simplify things to set the `$responsive` variable automatically depending on whether list of `$breakpoints` is empty or not? If no breakpoints have been defined, it's safe to assume we're not building a responsive project right? Something like this:

`$responsive: if(length($breakpoints) == 0, false, true);`

Of course, you may argue it's better to be explicit about setting `$responsive`? What do you think?

**Comment by csswizardry** [comment]
The only thing with that is you’d have to unset/remove all the stuff that alludes to responsiveness in order to turn it off, rather than just being able to leave it and control responsiveness via a variable. Kinda like having to remove your lighbulbs instead of just flicking the switch… :)

**Comment by emzo** [comment]
Sure, that's a fair point since you're providing a set of pre-defined breakpoints. I was coming at this form the "define your own breakpoints from the off" stance (which is kinda what this issue was about), but I accept many people will be more than happy to roll with the defaults. Thanks for the feedback!

**Comment by csswizardry** [comment]
Yeah definitely, it would always be nicer for stuff to be a little more intelligent (i.e. only being responsive if there are breakpoints) but as you say, because there are predefined ones it’s nicer to have a switch :)

**Comment by BPScott** [comment]
@emzo Initially I went down that route of checking list lengths instead of having an explicit $responsive variable (this would also have removed the need for $push and $pull), as I agree it is slightly more minimal and elegant, however I didn't want to break the existing convention of using $responsive to toggle if the responsive code should be included or not and that changing how that operates was outside of the scope of this PR.

> Kinda like having to remove your lighbulbs instead of just flicking the switch… :)

I'd be tempted to say it's more like ripping out all your fuses instead of flicking the master switch - Sure it's a bit more work than a single switch but at least they're all right next to each other rather than having to hunt around the house. But that's just me being contrary ;)

**Pull request closed without merging**
